export { default as getErDone } from "./1.png";
export { default as fourCast } from "./4-cast-screenshot.png";
export { default as plantarama } from "./plantarama-screenshot.png";
export { default as talkinTrash } from "./talkin-trash-screenshot.png";
export { default as mastermind } from "./mastermind-screenshot.png";
export { default as flyAway } from "./flyaway-screenshot.png";
export { default as battleboats } from "./battleboats-screenshot.png";
export { default as seddit } from "./seddit-screenshot.png";
export { default as shmurdle } from "./shmurdle-screenshot.png";
